name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "./ToDo-BooksStore.sln"
    - name: Build
      run: dotnet build "./ToDo-BooksStore.sln" --no-restore
    - name: Test
      run: dotnet test "./ToDo-BooksStore.sln" --no-build --verbosity normal
